### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by mrPassion78** [s4t4n/FS22_CVT_Addon#19]
could you maybe tell me what the difference is in:
- CVT classic 
- -CVT classic + IPM15
- --CVT classic + IPM27

I tried testing it out, and i have no idea.. ( sorry not a real farmer here).. i have noticed the difference in the classic and modern.. the modern stays in the lower rpm, and has more torqe at the bottom, the classic revs up to say 1800..

Thnx for this awesome mod.. its real fun!

**Comment by s4t4n** [comment]
The Inteeligent Power Management (IPM) should be based on this: [IPM JD Wiki](http://salesmanual.deere.com/sales/salesmanual/en_NA/tractors/attachments/engine/waterloo_common_intelligent_power_management.html)

 It's currently not working properly, it needs another way in the script to work better.  But the function is already prepared so that you can already select it.
 
There is also Tractor Implement Management (TIM), which can control certain aspects of the tractor via the ISObus.  But I'm not yet sure what devices can do.  But something will come at some point.
